---
abstract: 'Check that all files in the projects end correctly'
author:
  - 'Erik Carlsson <info@code301.com>'
build_requires:
  Test::More: '0.96'
configure_requires:
  Module::Build::Tiny: '0.037'
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.5, Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.140640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Dist-Zilla-Plugin-Test-EOF
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Test::EOF: '0.04'
  perl: '5.008005'
resources:
  bugtracker: https://github.com/Csson/p5-dist-zilla-plugin-test-eof/issues
  homepage: https://github.com/Csson/p5-dist-zilla-plugin-test-eof
  repository: https://github.com/Csson/p5-dist-zilla-plugin-test-eof.git
version: '0.02'
